# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/168Lsq3v1BBHVFpIzdKtDBEObaCt-tYQs
"""

class Difficulté:
    PARAMÈTRES_PAR_DÉFAUT = {
        "facile": {
            "vies": 5,
            "probabilité_bonus": 0.5,
            "vitesse_ennemis": 1.0,
            "santé_initiale": 100,
            "durée_max": 600,
            "pénalité": 5,
        },
        "moyen": {
            "vies": 3,
            "probabilité_bonus": 0.3,
            "vitesse_ennemis": 1.5,
            "santé_initiale": 75,
            "durée_max": 300,
            "pénalité": 10,
        },
        "difficile": {
            "vies": 1,
            "probabilité_bonus": 0.1,
            "vitesse_ennemis": 2.0,
            "santé_initiale": 50,
            "durée_max": 180,
            "pénalité": 20,
        },
    }

    def __init__(self, niveau):
        if niveau not in self.PARAMÈTRES_PAR_DÉFAUT:
            raise ValueError("Niveau invalide. Choisissez parmi : facile, moyen, difficile.")
        self.niveau = niveau
        self.paramètres = self.PARAMÈTRES_PAR_DÉFAUT[niveau]

    def get_paramètre(self, clé):
        return self.paramètres.get(clé, None)

    def __str__(self):
        return f"Difficulté : {self.niveau.capitalize()}, Paramètres : {self.paramètres}"