# -*- coding: utf-8 -*-
"""Map.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y3Nh48rvVaLXnDq91Vi7K4Pziy8zs89s
"""

class Map:
    TILE_EFFECTS = {
        0: "Wall",         # Infranchissable
        1: "Grass",        # Traversable
        2: "Forbidden",    # Réduit la santé
        3: "Shield"        # Bonus de santé/défense
    }

    def __init__(self, name, layout):
        """
        Initialise une carte.

        Paramètres
        ---------
        name : str
            Nom de la carte.
        layout : list[list[int]]
            Matrice représentant les types de cases (0, 1, 2, 3).
        """
        self.name = name
        self.layout = layout

    def get_tile_effect(self, x, y):
        """
        Renvoie l'effet de la case à une position donnée.

        Paramètres
        ---------
        x : int
            Coordonnée X.
        y : int
            Coordonnée Y.

        Retourne
        -------
        str : Effet de la case.
        """
        if 0 <= y < len(self.layout) and 0 <= x < len(self.layout[0]):
            return self.TILE_EFFECTS.get(self.layout[y][x], "Unknown")
        return "Out of bounds"

    def apply_tile_effect(self, unit, x, y):
        """
        Applique l'effet de la case à une unité.

        Paramètres
        ---------
        unit : Unit
            L'unité affectée.
        x : int
            Coordonnée X.
        y : int
            Coordonnée Y.
        """
        effect = self.get_tile_effect(x, y)
        if effect == "Forbidden":
            unit.health -= 10  # Réduit la santé de l'unité
            print(f"{unit.name} perd 10 PV en traversant un passage interdit!")
        elif effect == "Shield":
            unit.health += 5  # Augmente la santé de l'unité
            print(f"{unit.name} gagne 5 PV grâce à un bouclier!")

    def display(self):
        for row in self.layout:
            print(" ".join(str(tile) for tile in row))